// AUTO-GENERATED by scripts/build_pareto_table.py — DO NOT EDIT.
// Source: docs/pareto/bench_after.json (2026-08-23 11:49 UTC);
// Apple M-series (8 P-cores), MP-like spectra, eta = 1/sqrt(p).
//
// Preset intents:
//   speed    = fastest method with err <= 1e-02
//   accuracy = lowest error; ties within 1.05x resolved by runtime
//
#![allow(clippy::all)]

use super::StieltjesMethod;

/// Cumulative size bins (inclusive upper bound `p_max`, last bin = inf).
struct Bin {
    p_max: usize,
    speed_seq: StieltjesMethod,
    speed_par: StieltjesMethod,
    acc_seq: StieltjesMethod,
    acc_par: StieltjesMethod,
}

const BINS: &[Bin] = &[
    Bin {
        p_max: 1000,
        speed_seq: StieltjesMethod::ChebCode,
        speed_par: StieltjesMethod::BlockedTiled,
        acc_seq: StieltjesMethod::BlockedTiled,
        acc_par: StieltjesMethod::BlockedTiled,
    },
    Bin {
        p_max: 2000,
        speed_seq: StieltjesMethod::Fft2,
        speed_par: StieltjesMethod::ChebCode,
        acc_seq: StieltjesMethod::Blocked,
        acc_par: StieltjesMethod::Blocked,
    },
    Bin {
        p_max: 5000,
        speed_seq: StieltjesMethod::Fft5,
        speed_par: StieltjesMethod::ChebCode,
        acc_seq: StieltjesMethod::BlockedTiled,
        acc_par: StieltjesMethod::Blocked,
    },
    Bin {
        p_max: 10000,
        speed_seq: StieltjesMethod::Fft2,
        speed_par: StieltjesMethod::ChebCode,
        acc_seq: StieltjesMethod::BlockedTiled,
        acc_par: StieltjesMethod::Blocked,
    },
    Bin {
        p_max: 20000,
        speed_seq: StieltjesMethod::Fft2,
        speed_par: StieltjesMethod::ChebCode,
        acc_seq: StieltjesMethod::Blocked,
        acc_par: StieltjesMethod::Blocked,
    },
    Bin {
        p_max: 50000,
        speed_seq: StieltjesMethod::Fft2,
        speed_par: StieltjesMethod::ChebCode,
        acc_seq: StieltjesMethod::Blocked,
        acc_par: StieltjesMethod::Blocked,
    },
];

/// Look up the method chosen for `(intent, parallel, p)`.
pub(crate) fn pareto_pick(speed_intent: bool, parallel: bool, p: usize) -> StieltjesMethod {
    let bin = BINS
        .iter()
        .find(|b| p <= b.p_max)
        .unwrap_or_else(|| BINS.last().expect("non-empty BINS"));
    match (speed_intent, parallel) {
        (true, false) => bin.speed_seq,
        (true, true) => bin.speed_par,
        (false, false) => bin.acc_seq,
        (false, true) => bin.acc_par,
    }
}
