#!/usr/bin/env python3
"""Build the data-driven preset decision table from a pareto_data JSON dump.

Reads docs/pareto/bench_after.json, computes the per-size Pareto winners for
the two preset intents, and emits src/config/pareto_autogen.rs — a static
lookup table consumed by `StieltjesMethod::resolve` / `Strategy`.

Selection rules (documented in the generated file):
  * speed    : fastest method with rel-error <= SPEED_ERR_CAP
               (pure-speed intent; the cap only excludes pathological picks)
  * accuracy : minimum error; ties within ACC_TIE_BAND of the best error are
               broken by runtime

Parallelism is a table dimension: seq and rayon get independent columns.
"""
import argparse
import datetime
import json
import pathlib

SPEED_ERR_CAP = 1e-2  # exclude >1% picks from the Speed intent
ACC_TIE_BAND = 1.05   # "equal accuracy" = within 5% relative L2 of the best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bench_json")
    ap.add_argument("--out", default="src/config/pareto_autogen.rs")
    args = ap.parse_args()

    with open(args.bench_json) as f:
        data = json.load(f)

    rows = {}
    for r in data["rows"]:
        rows.setdefault((r["par"], r["p"]), []).append(r)

    sizes = sorted({p for (_, p) in rows})
    pars = ["seq", "rayon"]

    # winners[(intent, par)] = [(p_max, method), ...] cumulative bins
    bins = {p: {} for p in sizes}

    for par in pars:
        for p in sizes:
            rs = rows.get((par, p), [])
            if not rs:
                continue

            def pick_speed():
                ok = [r for r in rs if r["err"] <= SPEED_ERR_CAP]
                pool = ok if ok else sorted(rs, key=lambda r: r["err"])[:1]
                return min(pool, key=lambda r: r["ms"])

            def pick_accuracy():
                best_err = min(r["err"] for r in rs)
                band = [r for r in rs if r["err"] <= best_err * ACC_TIE_BAND]
                return min(band, key=lambda r: r["ms"])

            bins[p][par] = {
                "speed": pick_speed(),
                "accuracy": pick_accuracy(),
            }

    # Emit Rust -----------------------------------------------------------
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "// AUTO-GENERATED by scripts/build_pareto_table.py — DO NOT EDIT.",
        f"// Source: {args.bench_json} ({ts});",
        "// Apple M-series (8 P-cores), MP-like spectra, eta = 1/sqrt(p).",
        "//",
        "// Preset intents:",
        f"//   speed    = fastest method with err <= {SPEED_ERR_CAP:.0e}",
        f"//   accuracy = lowest error; ties within {ACC_TIE_BAND:.2f}x resolved by runtime",
        "//",
        "#![allow(clippy::all)]",
        "",
        "use super::StieltjesMethod;",
        "",
        "/// Cumulative size bins (inclusive upper bound `p_max`, last bin = inf).",
        "struct Bin {",
        "    p_max: usize,",
        "    speed_seq: StieltjesMethod,",
        "    speed_par: StieltjesMethod,",
        "    acc_seq: StieltjesMethod,",
        "    acc_par: StieltjesMethod,",
        "}",
        "",
        "const BINS: &[Bin] = &[",
    ]
    for p in sizes:
        b = bins[p]
        lines.append(
            f"    Bin {{ p_max: {p}, "
            f"speed_seq: StieltjesMethod::{rust_variant(b['seq']['speed']['method'])}, "
            f"speed_par: StieltjesMethod::{rust_variant(b['rayon']['speed']['method'])}, "
            f"acc_seq: StieltjesMethod::{rust_variant(b['seq']['accuracy']['method'])}, "
            f"acc_par: StieltjesMethod::{rust_variant(b['rayon']['accuracy']['method'])} }},"
        )
    lines += [
        "];",
        "",
        "/// Look up the method chosen for `(intent, parallel, p)`.",
        "pub(crate) fn pareto_pick(speed_intent: bool, parallel: bool, p: usize) -> StieltjesMethod {",
        "    let bin = BINS",
        "        .iter()",
        "        .find(|b| p <= b.p_max)",
        "        .unwrap_or_else(|| BINS.last().expect(\"non-empty BINS\"));",
        "    match (speed_intent, parallel) {",
        "        (true, false) => bin.speed_seq,",
        "        (true, true) => bin.speed_par,",
        "        (false, false) => bin.acc_seq,",
        "        (false, true) => bin.acc_par,",
        "    }",
        "}",
        "",
    ]
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")
    for p in sizes:
        b = bins[p]
        for par in pars:
            sp, ac = b[par]["speed"], b[par]["accuracy"]
            print(
                f"  p<={p:>6} {par:>5}: speed={sp['method']:<14}"
                f"({sp['ms']:8.3f} ms, err {sp['err']:.1e})"
                f" | accuracy={ac['method']:<12}"
                f"({ac['ms']:8.3f} ms, err {ac['err']:.1e})"
            )


# bench method name -> StieltjesMethod variant (explicit: ChebCode etc.
# are camel-cased, not simple capitalization).
RUST_VARIANTS = {
    "naive": "Naive",
    "autovec": "AutoVectorized",
    "blocked": "Blocked",
    "blocked_tiled": "BlockedTiled",
    "blocked_windowed": "BlockedWindowed",
    "windowed_cut10": "BlockedWindowed",
    "adaptive": "Adaptive",
    "fft5": "Fft5",
    "fft3": "Fft3",
    "fft2": "Fft2",
    "fmm": "TreeCode",
    "chebcode": "ChebCode",
}


def rust_variant(name: str) -> str:
    try:
        return RUST_VARIANTS[name]
    except KeyError as e:
        raise SystemExit(f"unknown method name in bench data: {name!r}") from e


if __name__ == "__main__":
    main()
